services:
  - type: static
    name: f1-frontend
    runtime: static
    buildCommand: cd src/frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./src/frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://f1-api.onrender.com
      - key: CI
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable